#ifndef VECTORIZER_OPTIONS_H_Dmkow3kf0934fmvtrklmvruiegvrtgerjfiuewjfoiewjkfd9e8fhgvnjkfdgvcvcxvxcvxcvcxveffewfewttrhgthth
#define VECTORIZER_OPTIONS_H_Dmkow3kf0934fmvtrklmvruiegvrtgerjfiuewjfoiewjkfd9e8fhgvnjkfdgvcvcxvxcvxcvcxveffewfewttrhgthth

#include <boost/program_options/options_description.hpp>

namespace vectorizer
{
	boost::program_options::options_description setup_options();
}

#endif