#ifndef VECTORIZER_INTERFACE_TYPES_H_mf3ifj4389fj4fwfwefwefwefjioefasfasfafwfwejflsakmdkjsfsdfsdfafanfiknejdwejdoijweoifdj23498f54jgfrekjnkf
#define VECTORIZER_INTERFACE_TYPES_H_mf3ifj4389fj4fwfwefwefwefjioefasfasfafwfwejflsakmdkjsfsdfsdfafanfiknejdwejdoijweoifdj23498f54jgfrekjnkf

#include <common/preprocessor_interface_types.h>

namespace vectorizer
{
	typedef preprocessor::output input;

	class output
	{};
}

#endif